In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./datasets/November_2021/20211109_drug_trials_filtered.csv')

In [3]:
df.head()

,Unnamed: 0,index,Rank,Acronym,ArmGroupDescription,ArmGroupInterventionName,ArmGroupLabel,ArmGroupType,BriefSummary,BriefTitle,...,StdAge,StudyFirstPostDate,StudyFirstPostDateType,StudyFirstSubmitDate,StudyFirstSubmitQCDate,StudyPopulation,StudyType,VersionHolder,WhyStopped,Placebo
0,5,5,6,Lisphem,Li+ is an FDA (NDA: 016834) and ANSM (AMM 3400...,Drug: Lithium Carbonate|Drug: Placebo,Lithium|Placebo,Experimental|Placebo Comparator,There is currently no treatment for the body s...,Effect of Lithium in Patients With Autism Spec...,...,Child|Adult,"November 10, 2020",Actual,"November 5, 2020","November 9, 2020",NaN,Interventional,"November 09, 2021",NaN,Yes
1,13,13,14,NaN,intranasal ketamine and dexmedetomidine was tr...,Drug: ketamine and dexmedetomidine|Drug: ketam...,ketamine and dexmedetomidine group|ketamine gr...,Experimental|Experimental|Placebo Comparator,Autism spectrum disorder (ASD) is a life-long ...,Intranasal Ketamine With Dexmedetomidine for t...,...,Child,"February 15, 2018",Actual,"January 28, 2018","February 9, 2018",NaN,Interventional,"November 09, 2021",NaN,No
2,28,28,29,Autism,"15 mg/kg oral solution three times per day, ma...",Drug: EPI-743,EPI-743,Experimental,The investigators hypothesize that EPI-743 may...,An Exploratory Open Label Study of EPI-743 (Vi...,...,Child,"August 27, 2014",Estimate,"August 21, 2014","August 25, 2014",NaN,Interventional,"November 09, 2021",This study was halted prior to enrolling.,No
3,39,39,40,NaN,Participants in the placebo arm will receive p...,Drug: Memantine|Other: Placebo,Memantine|Placebo|Control Group,Experimental|Placebo Comparator|No Intervention,"This study is a 12-week, randomized-controlled...",Behavioral and Neural Response to Memantine in...,...,Child,"October 30, 2013",Estimate,"October 24, 2013","October 29, 2013",NaN,Interventional,"November 09, 2021",NaN,Yes
4,41,41,42,NaN,Patients with Phelan-McDermid syndrome receive...,Drug: Recombinant human Growth hormone,Phelan-McDermid syndrome,Experimental,Phelan McDermid syndrome (PMS) is a rare genet...,Growth Hormone Treatment in Children With Phel...,...,Child,"July 1, 2019",Actual,"June 27, 2019","June 27, 2019",NaN,Interventional,"November 09, 2021",NaN,No

In [8]:
df.describe(include = 'all')

,Unnamed: 0,index,Rank,Acronym,ArmGroupDescription,ArmGroupInterventionName,ArmGroupLabel,ArmGroupType,BriefSummary,BriefTitle,...,StdAge,StudyFirstPostDate,StudyFirstPostDateType,StudyFirstSubmitDate,StudyFirstSubmitQCDate,StudyPopulation,StudyType,VersionHolder,WhyStopped,Placebo
count,314.000000,314.000000,314.000000,88,255,297,297,297,314,314,...,314,314,314,314,314,0.0,314,314,33,314
unique,NaN,NaN,NaN,84,250,261,258,37,313,312,...,5,290,2,284,290,NaN,1,1,33,2
top,NaN,NaN,NaN,Omega Heroes,NNZ-2591 oral solution (50mg/mL) to be adminis...,Drug: Aripiprazole,1|2,Experimental|Placebo Comparator,This Phase IIb study is designed to assess whe...,Intranasal Oxytocin and Learning in Autism,...,Child,"September 21, 2005",Estimate,"September 13, 2005","September 13, 2005",NaN,Interventional,"November 09, 2021",Study terminated due to enrollment challenges ...,Yes
freq,NaN,NaN,NaN,2,2,6,6,90,2,2,...,175,4,221,5,5,NaN,314,314,1,165
mean,755.197452,439.910828,756.197452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,386.835923,307.747020,386.835923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,5.000000,0.000000,6.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,473.000000,155.000000,474.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,788.500000,396.000000,789.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1063.000000,712.750000,1064.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1648.000000,998.000000,1649.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Questions to Answer

1) How many trials were terminated, and for what reasons?

2) What is the most common drug tested, and the second, and the third most common?

3) How many studies have actually posted results?

4) What fraction of studies that have been completed have posted results?

5) What are the most common conditions, and in what fractions?

6) What fraction of drugs in clinical trials have been approved for another condition?

7) What are the commonly occuring 'combined modality' types? Comment specifically on those trials.

8) What is the earliest trial? The latest trial?

9) Put together descriptive statistics on the 'Lead Author Country'.

10) Who sponsors most studies? Industry or academia?

11) What are the ranges of minimum and maximum ages?